name: OHW20
channels:
  - conda-forge
dependencies:
  - python=3.8
  - argopy
  - bokeh
  - cartopy
  - cdsapi
  - cf-units
  - colorcet
  - datashader
  - erddapy
  - geolinks
  - geopandas
  - geoviews
  - gsw
  - holoviews
  - hvplot
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - jupyter
  - jupyter-rsession-proxy
  - matplotlib-base
  - nc-time-axis
  - netcdf4
  - numpy
  - palettable
  - pandas
  - panel
  - param
  - podaacpy
  - pyoos
  - rasterio
  - requests
  - retrying
  - seaborn
  - shapely
  - siphon
  - xarray
  - xlrd
  # R packages
  - r-base
  # - r-phyloseq (not in cran)
  - r-ape
  - r-cowplot
  - r-crul
  - r-dplyr
  - r-ggplot2
  - r-gridextra
  - r-gsw
  - r-irkernel
  - r-leaflet
  - r-magrittr
  - r-mapdata
  - r-maps
  - r-maptools
  - r-ncdf4
  - r-oce
  - r-patchwork
  - r-plotly
  - r-raster
  - r-rcolorbrewer
  - r-readr
  - r-scales
  - r-tidyverse
  - r-vegan
  - rpy2
  # extras
  - conda-lock
  - emacs
  - git
  - graphviz
  - unzip
  - vim
  - zip
