name: OHW-py
channels:
  - conda-forge
  - bioconda
dependencies:
  # base
  - python=3.9
  - pangeo-notebook=2023.07.21
  - nb_conda_kernels
  - curl
  - git
  - wget
  - tar
  - vim
  - gh
  - nano
  - mamba
  - gh-scoped-creds # github auth via https://docs.2i2c.org/data/git/
  # JupyterLab language packs
  - jupyterlab-language-pack-es-ES
  - jupyterlab-language-pack-pt-BR
  # Python packages
  - argopy>=0.1.7
  - bokeh
  - bottleneck
  - cartopy
  - cdsapi
  - cf-units
  - cf_xarray
  - cmocean
  - colorcet
  - compilers
  - compliance-checker
  - conda-lock
  - contextily
  - ctd
  # - dask  # supplied by pangeo-notebook
  # - dask-gateway=2022.6.1 # 2022.6.1 is what 2i2c is set to, and needs to match underlying dask-gateway-server on cluster. Supplied by pangeo-notebook
  # - dask-labextension # supplied by pangeo-notebook
  - datashader
  - descartes
  # - distributed # supplied by pangeo-notebook
  - echopy
  - echopype
  - erddapy
  - fastparquet
  - ffmpeg
  - folium
  - fsspec
  - gcsfs
  - geolinks
  - geopandas
  - geoviews
  - graphviz
  - gsw
  - h5netcdf
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-xarray
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - ipywidgets # supplied by pangeo-notebook
  # - jupyter # brings in QT, and JupyterLab only needs jupyter_core
  # - jupyter-rsession-proxy
  # - jupyer-server-proxy # supplied by pangeo-notebook
  - jupyter_contrib_nbextensions
  # - jupyterlab # supplied by pangeo-notebook
  - jupyterlab-git
  # - jupyterhub>=2.3.1  # 2.3.1 is the minimum required by 2i2c, and is supplied by pangeo-notebook
  # - jupterhub-singleuser  # supplied by pangeo-notebook
  - matplotlib-base
  - movingpandas
  # - nbgitpuller  # supplied by pangeo-notebook
  - nc-time-axis
  - netcdf4
  - numpy
  - openpyxl
  - palettable
  - pandas
  - panel
  - param
  - parcels
  - podaacpy
  - pyoos
  - python-snappy
  - rasterio
  - rasterstats
  - regionmask
  - requests
  - retrying
  - rioxarray
  # 2/12/23: Caused error during mamba env create
  # - rise
  - s3fs
  - scipy
  - seaborn
  - searvey
  - seawater
  # 2/15/2023: Heads-up: shapely 2.0 may be causing havoc,
  # and it may be a good idea to pin it to <2
  - shapely
  - siphon
  # - tensorflow-cpu # keras and tensorflow cause our images to become much larger
  # Which can cause problems with Github Actions running out of storage https://github.com/docker/build-push-action/issues/321
  - unzip
  - windrose
  - xarray
  - xesmf
  - xgcm
  # - xlrd  # deprecated, use openpyxl instead
  - zarr
  # Tutorial specific, may be dupes to make things explicit
  - kaiju # 23-Julia
  - scikit-learn # 23-Julia
  - fastq-dl # 23-Julia
  - seqtk # 23-Julia
  - pandas # 23-Julia
  - matplotlib-base # 23-Julia
  - seaborn # 23-Julia
  - pandas # 23-Myranda
  - xarray # 23-Myranda
  - seaborn # 23-Myranda
  - matplotlib-base # 23-Myranda
  - argopy # 23-Myranda
  - cartopy # 23-Myranda
  - owslib # 23-Marty
  - pandas # 23-Marty
  - xarray # 23-Marty
  - cartopy # 23-Marty
  - holoviews # 23-Marty
  - hvplot # 23-Marty
  - geoviews # 23-Marty
  - netcdf4 # 23-Marty
  - s3fs # 23-Marty
  - zarr # 23-Marty
  - h5netcdf # 23-Marty
  - scikit-learn # 23-Filipe
  - scikit-image # 23-Filipe
  - pillow # 23-Filipe
