name: OHW-py
channels:
  - conda-forge
  - bioconda
dependencies:
  # base
  - python=3.9
  - pangeo-notebook=2023.02.11
  - nb_conda_kernels
  - curl
  - git
  - wget
  - tar
  - vim
  - gh
  - nano
  # JupyterLab language packs
  - jupyterlab-language-pack-es-ES
  - jupyterlab-language-pack-pt-BR
  # Python packages
  - argopy>=0.1.7
  - bokeh
  - bottleneck
  - cartopy
  - cdsapi
  - cf-units
  - cf_xarray
  - cmocean
  - colorcet
  - compilers
  - compliance-checker
  - conda-lock
  - contextily
  - ctd
  # - dask  # supplied by pangeo-notebook
  # - dask-gateway=2022.6.1 # 2022.6.1 is what 2i2c is set to, and needs to match underlying dask-gateway-server on cluster. Supplied by pangeo-notebook
  # - dask-labextension # supplied by pangeo-notebook
  - datashader
  - descartes
  # - distributed # supplied by pangeo-notebook
  - echopy
  - echopype
  - erddapy
  - fastparquet
  - ffmpeg
  - folium
  - fsspec
  - gcsfs
  - geolinks
  - geopandas
  - geoviews
  - graphviz
  - gsw
  - h5netcdf
  - holoviews
  - hvplot
  - intake
  - intake-esm
  - intake-xarray
  - ioos-tools
  - ioos_qc
  - ipyleaflet
  - ipywidgets # supplied by pangeo-notebook
  - jupyter
  # - jupyter-rsession-proxy
  # - jupyer-server-proxy # supplied by pangeo-notebook
  - jupyter_contrib_nbextensions
  # - jupyterlab # supplied by pangeo-notebook
  - jupyterlab-git
  # - jupyterhub>=2.3.1  # 2.3.1 is the minimum required by 2i2c, and is supplied by pangeo-notebook
  # - jupterhub-singleuser  # supplied by pangeo-notebook
  - matplotlib-base
  - movingpandas
  # - nbgitpuller  # supplied by pangeo-notebook
  - nc-time-axis
  - netcdf4
  - numpy
  - openpyxl
  - palettable
  - pandas
  - panel
  - param
  - parcels
  - podaacpy
  - pyoos
  - python-snappy
  - rasterio
  - rasterstats
  - regionmask
  - requests
  - retrying
  - rioxarray
  # 2/12/23: Caused error during mamba env create
  # - rise
  - s3fs
  - scipy
  - seaborn
  - searvey
  - seawater
  # 2/15/2023: Heads-up: shapely 2.0 may be causing havoc,
  # and it may be a good idea to pin it to <2
  - shapely
  - siphon
  - tensorflow-cpu
  - unzip
  - windrose
  - xarray
  - xesmf
  - xgcm
  # - xlrd  # deprecated, use openpyxl instead
  - zarr

  # Julia Brown's Tutorial
  - nextflow
  - kaiju
  - kraken2
