name: OHW-r
channels:
  - conda-forge
dependencies:
  # base
  - python=3.10
  - pangeo-notebook=2022.07.12
  - nb_conda_kernels
  # - curl
  # - git
  # - wget
  # - tar
  # - vim
  # R packages
  - r-base >=4
  - r-abind
  - r-akima
  - r-ape
  - r-automap
  - r-biomod2
  - r-bitops
  - r-caret
  - r-catools
  - r-checkmate
  - r-commonmark
  - r-cowplot
  - r-crul
  - r-dbi
  - r-devtools
  - r-dismo
  - r-doparallel
  - r-dplyr
  - r-earth
  - r-foreach
  - r-foreign
  - r-gbm >=2.1.3
  - r-geometry
  - r-geosphere
  - r-ggplot2
  - r-glmnet
  - r-gridextra
  - r-gsw
  - r-hexbin
  - r-httpcache
  - r-httr
  - r-irkernel
  - r-jsonlite
  - r-keras
  - r-knitr
  - r-lattice
  - r-leaflet
  - r-littler
  - r-lpsolve
  - r-lubridate
  - r-mapdata
  - r-mapedit
  - r-maps
  - r-maptools
  - r-marmap
  - r-mass
  - r-mda
  - r-ncdf4
  - r-nnet
  - r-oce
  - r-ocedata
  - r-patchwork
  - r-plotly
  - r-proc >=1.15.0
  - r-ps>=1.3.4
  - r-purrr
  - r-r.utils
  - r-randomforest
  - r-rann
  - r-raster >=1.4.3
  - r-rastervis
  - r-readr
  - r-remotes
  - r-reshape
  - r-rgdal >=1.5
  - r-rgeos
  - r-rlang
  - r-rmarkdown
  - r-rnaturalearth
  - r-rnaturalearthdata
  - r-robis
  - r-rpart
  - r-rsqlite
  - r-rstackdeque
  - r-s2
  - r-sf >=0.9_5
  - r-sp
  - r-tibble
  - r-tidyr
  - r-tidyverse
  - r-tiff
  - r-tzdb
  - r-vegan
  - r-vroom
  - r-wdpar
  - r-xml2
  - rpy2
