name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        description: What directory should the image be built from
        required: true
      image_name:
        type: string
        description: Name of Docker image
        required: true
      image_tag:
        type: string
        description: Tag for Docker image
        required: true
      push_image:
        type: boolean
        description: Should the image be pushed to the Github Container Registry
        required: false
        default: false

  workflow_dispatch:
    inputs:
      working_directory:
        type: string
        description: What directory should the image be built from
        required: true
      image_name:
        type: string
        description: Name of Docker image
        required: true
      image_tag:
        type: string
        description: Tag for Docker image
        required: true
      push_image:
        type: boolean
        description: Should the image be pushed to the Github Container Registry
        required: false
        default: false

jobs:
  build-image:
    runs-on: ubuntu-22.04
    name: Build and push image
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.5.1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ohw-docker-buildx-${{ inputs.image_name }}-${{ github.sha }}
          restore-keys: |
            ohw-docker-buildx-${{ inputs.image_name }}

      - name: Set Job Environment Variables
        run: |
          SHA7="${GITHUB_SHA::7}"
          DOCKER_TAG=$SHA7
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}"
          echo "DOCKER_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Build Docker Image
        uses: docker/build-push-action@v2.6.1
        with:
          tags: |
            ${{ env.IMAGE_NAME }}:${{ DOCKER_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: false
          load: true
          working-directory: ${{ inputs.working_directory }}

      - name: Docker image sizes
        run: |
          docker images

          echo "### Image sizes" >> $GITHUB_STEP_SUMMARY
          docker images >> $GITHUB_STEP_SUMMARY

      - name: Export Full Conda Environment
        run: |
          docker run ${{ env.IMAGE_NAME }}:${{ DOCKER_TAG }} conda list --explicit > conda-packages.txt

          echo "### Conda Environment" >> $GITHUB_STEP_SUMMARY
          cat conda-packages.txt >> $GITHUB_STEP_SUMMARY

      - name: Archive Conda Package List
        uses: actions/upload-artifact@v1
        with:
          name: conda-packages
          path: conda-packages.txt

      - name: "Log into GitHub Container Registery"
        uses: docker/login-action@v1.9.0
        if: ${{ inputs.push_image}}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        if: ${{ inputs.push_image }}
        run: docker push ${{ env.IMAGE_NAME }}:${{ DOCKER_TAG }}

      - name: Move Docker Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
