name: MasterBuild

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

env:
  GHCR_CONTAINER_NAME: ghcr.io/${{ github.repository_owner }}/jupyer-image
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
      
    - name: Cache Docker layers
      uses: actions/cache@v2.1.6
      with:
        path: /tmp/.buildx-cache
        key: ohw-docker-buildx-${{ github.sha }}
        restore-keys: |
          ohw-docker-buildx-

    - name: Set Job Environment Variables
      run: |
        SHA7="${GITHUB_SHA::7}"
        DOCKER_TAG=$SHA7
        IMAGE_SPEC="${GHCR_CONTAINER_NAME}:${DOCKER_TAG}"
        echo "DOCKER_TAG=${DOCKER_TAG}" >> $GITHUB_ENV
        echo "IMAGE_SPEC=${IMAGE_SPEC}" >> $GITHUB_ENV


    - name: "Log into GitHub Container Registery"
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      uses: docker/build-push-action@v2.6.1
      with:
        tags: |
          ${{ env.GHCR_CONTAINER_NAME }}:latest
          ${{ env.IMAGE_SPEC }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        push: false
        load: true

    - name: Push latest Docker image to Github Container Registry
      run: docker push ${{ env.GHCR_CONTAINER_NAME }}:latest

    - name: Push tagged Docker image to Github Container Registry
      run: docker push ${{ env.IMAGE_SPEC }}

    - name: Export Full Conda Environment
      run: |
        docker run ${{ env.IMAGE_SPEC }} conda list --explicit > conda-packages.txt

    - name: Archive Conda Package List
      uses: actions/upload-artifact@v1
      with:
        name: conda-packages
        path: conda-packages.txt

    - name: Docker image sizes
      run: docker images
    
    - name: Move Docker Cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
