# Only test building images
name: PullRequestBuild

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'

env:
  # CONTAINER_NAME: uwhackweeks/oceanhackweek using personal account till push permissions get figured out
  CONTAINER_NAME: abkfenris/oceanhackweek
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
      
    - name: Cache Docker layers
      uses: actions/cache@v2.1.6
      with:
        path: /tmp/.buildx-cache
        key: ohw-docker-buildx-${{ github.sha }}
        restore-keys: |
          ohw-docker-buildx-

    - name: Build Docker Image
      uses: docker/build-push-action@v2.6.1
      with:
        push: false
        tags: ${{ env.CONTAINER_NAME }}:PR
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
        load: true
        context: .

    - name: Export Full Conda Environment
      run: |
        docker run ${CONTAINER_NAME}:PR conda list --explicit > conda-packages.txt

    - name: Archive Conda Package List
      uses: actions/upload-artifact@v1
      with:
        name: conda-packages
        path: conda-packages.txt
    
    - name: Docker image sizes
      run: docker images
    
    - name: Move Docker Cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
